# Filebeat 配置：采集 stream_flow.log 并发送到 Logstash
# 路径以容器内为准，宿主机 ./logs 挂载为 /app/logs
#
# 性能优化：使用较长的 scan_frequency 和 harvester_buffer_size 减少 IO

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/stream_flow.log
    # 不在 Filebeat 解析 JSON，交给 Logstash 处理（更灵活）
    # 每行是完整的 JSON 对象，直接作为 message 发送
    close_inactive: 2h
    ignore_older: 168h
    # 性能优化：降低扫描频率，减少 CPU 占用
    scan_frequency: 10s
    # 增大读取缓冲区，减少系统调用
    harvester_buffer_size: 32768
    # 限制单行最大长度（防止异常大日志撑爆内存）
    max_bytes: 1048576

output.logstash:
  hosts: ["logstash:5044"]
  # 降低批量大小，减少内存占用
  bulk_max_size: 1024
  timeout: 30
  # 启用压缩减少网络带宽
  compression_level: 3

processors:
  - add_host_metadata: ~

# 日志级别设为 warning，减少 Filebeat 自身日志输出
logging.level: warning
logging.to_stderr: true

# 限制 Filebeat 自身内存使用
queue.mem:
  events: 2048
  flush.min_events: 512
  flush.timeout: 5s
