# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/intent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/intent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/intent.proto\x12\x06intent\"\xc6\x01\n\x0f\x43lassifyRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x35\n\x07\x63ontext\x18\x03 \x03(\x0b\x32$.intent.ClassifyRequest.ContextEntry\x12\x11\n\tuse_cache\x18\x04 \x01(\x08\x12\x16\n\x0eprompt_version\x18\x05 \x01(\t\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb8\x01\n\x10\x43lassifyResponse\x12\x0f\n\x07intents\x18\x01 \x03(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x12\n\nrule_types\x18\x03 \x03(\t\x12\x10\n\x08keywords\x18\x04 \x03(\t\x12\x11\n\treasoning\x18\x05 \x01(\t\x12\x14\n\x0cis_ambiguous\x18\x06 \x01(\x08\x12\x16\n\x0eprompt_version\x18\x07 \x01(\t\x12\x18\n\x10response_time_ms\x18\x08 \x01(\x03\"A\n\x14\x42\x61tchClassifyRequest\x12)\n\x08requests\x18\x01 \x03(\x0b\x32\x17.intent.ClassifyRequest\"D\n\x15\x42\x61tchClassifyResponse\x12+\n\tresponses\x18\x01 \x03(\x0b\x32\x18.intent.ClassifyResponse\"\x14\n\x12HealthCheckRequest\"N\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x16\n\x0eprompt_version\x18\x03 \x01(\t2\xe4\x01\n\rIntentService\x12=\n\x08\x43lassify\x12\x17.intent.ClassifyRequest\x1a\x18.intent.ClassifyResponse\x12L\n\rBatchClassify\x12\x1c.intent.BatchClassifyRequest\x1a\x1d.intent.BatchClassifyResponse\x12\x46\n\x0bHealthCheck\x12\x1a.intent.HealthCheckRequest\x1a\x1b.intent.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.intent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLASSIFYREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_CLASSIFYREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_CLASSIFYREQUEST']._serialized_start=31
  _globals['_CLASSIFYREQUEST']._serialized_end=229
  _globals['_CLASSIFYREQUEST_CONTEXTENTRY']._serialized_start=183
  _globals['_CLASSIFYREQUEST_CONTEXTENTRY']._serialized_end=229
  _globals['_CLASSIFYRESPONSE']._serialized_start=232
  _globals['_CLASSIFYRESPONSE']._serialized_end=416
  _globals['_BATCHCLASSIFYREQUEST']._serialized_start=418
  _globals['_BATCHCLASSIFYREQUEST']._serialized_end=483
  _globals['_BATCHCLASSIFYRESPONSE']._serialized_start=485
  _globals['_BATCHCLASSIFYRESPONSE']._serialized_end=553
  _globals['_HEALTHCHECKREQUEST']._serialized_start=555
  _globals['_HEALTHCHECKREQUEST']._serialized_end=575
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=577
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=655
  _globals['_INTENTSERVICE']._serialized_start=658
  _globals['_INTENTSERVICE']._serialized_end=886
# @@protoc_insertion_point(module_scope)
